{
 "title": "Automation Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Website Baseline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "website_baseline" }
   ]
  },
  {
   "title": "Desktop failure count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "website_baseline{job='desktop'}",
     "legendFormat": "{{failed}}"
    }
   ]
  },
  {
   "title": "MDot failure count",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 8 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "website_baseline{job='mdot'}", "legendFormat": "{{failed}}" }
   ]
  }
 ]
}